# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: scm-linux
    main: ./cmd/scm/scm.go
    binary: scm
    ldflags:
      - -X github.com/garethjevans/scm/pkg/version.Version={{.Version}} -X github.com/garethjevans/scm/pkg/version.Revision={{.ShortCommit}} -X github.com/garethjevans/scm/pkg/version.BuildDate={{.CommitDate}} -X github.com/garethjevans/scm/pkg/version.BuiltBy=goreleaser
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le

  - id: scm-darwin
    main: ./cmd/scm/scm.go
    binary: scm
    ldflags:
      - -X github.com/garethjevans/scm/pkg/version.Version={{.Version}} -X github.com/garethjevans/scm/pkg/version.Revision={{.ShortCommit}} -X github.com/garethjevans/scm/pkg/version.BuildDate={{.CommitDate}} -X github.com/garethjevans/scm/pkg/version.BuiltBy=goreleaser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: scm-windows-amd64
    main: ./cmd/scm/scm.go
    binary: scm
    ldflags:
      - -X github.com/garethjevans/scm/pkg/version.Version={{.Version}} -X github.com/garethjevans/scm/pkg/version.Revision={{.ShortCommit}} -X github.com/garethjevans/scm/pkg/version.BuildDate={{.CommitDate}} -X github.com/garethjevans/scm/pkg/version.BuiltBy=goreleaser
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

release:
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"

brews:
  - name: scm
    repository:
      owner: garethjevans
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: garethjevans
      email: gareth@bryncynfelin.co.uk
    directory: Formula
    description: "Utility to validate a component structure"
