apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://gitlab.com
  name: git-ssh2
  namespace: dev
stringData:
  password: a-random-password
  username: a-username
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://gitlab.com/org/repo
  name: git-ssh3
  namespace: dev
stringData:
  password: a-random-token
  username: a-username
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://dev.azure.com
  name: git-ssh4
  namespace: dev
stringData:
  password: azure-token
  username: a-username
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh5
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: <private-key>
  known_hosts: <known-hosts>
