---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: scm-
spec:
  params:
    - name: message
      value: "hello world!"
  taskSpec:
    steps:
    - name: default
      image: golang:1.20-alpine
      script: |
        echo "displaying credentials"
        cat $(credentials.path)/.git-credentials
        echo ""

        echo "installing scm"
        go install github.com/garethjevans/scm/cmd/scm@main
        echo ""

        echo "displaying help"
        scm --help
        echo ""
       
        echo "calculating url" 
        scm url --host https://github.com --owner garethjevans --repo scm
        echo ""

        echo "determining token 0"
        scm token --host https://github.com --path $(credentials.path)/.git-credentials
        echo ""

        echo "determining token 1"
        scm token --host https://gitlab.com --path $(credentials.path)/.git-credentials
        echo ""

        echo "determining token 2"
        scm token --host https://gitlab.com --owner org --repo repo --path $(credentials.path)/.git-credentials
        echo ""
        
        echo "determining token 3"
        scm token --host https://dev.azure.com --owner org --repo repo --path $(credentials.path)/.git-credentials
        echo ""


